services:
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        restart: unless-stopped
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
    mongodb:
        image: mongo:6.0
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
            - ./mongo/data:/data/db
            - ./mongo/init:/docker-entrypoint-initdb.d